version: '3.1'
# Los puertos se pueden dejar de publicar si tenemos el haproxy, porque se ven todos desde la misma red del compos
# Solo hay que dejar los puertos expuestos en haproxy
services:
  order:
    container_name: order
    build: ./order
    volumes:
      - ./order:/app
#    ports:
#      - 8000:8000/tcp
    environment:
      GUNICORN_PORT: '${GUNICORN_PORT}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI_ORDER}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
    restart: on-failure
<<<<<<< HEAD
  auth:
    container_name: auth
    build: ./auth
    volumes:
      - ./auth/auth:/app
    ports:
      - 8001:8000/tcp
=======
    depends_on:
      - rabbitmq
  client:
    container_name: client
    build: ./client
    volumes:
      - ./client:/app
#    ports:
#      - 8001:8000/tcp
>>>>>>> ba2686b1ef16a094943a67b59b3819141dba7513
    environment:
      GUNICORN_PORT: '${GUNICORN_PORT}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI_CLIENT}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
    restart: on-failure
    depends_on:
      - rabbitmq
  payment:
    container_name: payment
    build: ./payment
    volumes:
      - ./payment:/app
#    ports:
#      - 8002:8000/tcp
    environment:
      GUNICORN_PORT: '${GUNICORN_PORT}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI_PAYMENT}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
    restart: on-failure
    depends_on:
      - rabbitmq
  haproxy:
    container_name: haproxy
    image: haproxy:latest
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - '${HA_PROXY_PORT}:${HA_PROXY_PORT}'
      - '${HA_PROXY_STATS_PORT}:${HA_PROXY_STATS_PORT}'
    environment:
      HA_PROXY_STATS_PORT: '${HA_PROXY_STATS_PORT}'
      HA_PROXY_PORT: '${HA_PROXY_PORT}'
    restart: on-failure
  machine:
    container_name: machine
    build: ./machine
    volumes: 
      - ./machine:/app
#    ports:
#      - 8003:8000
    environment:
      GUNICORN_PORT: '${GUNICORN_PORT}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI_MACHINE}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
    restart: on-failure
    depends_on:
      - rabbitmq
  delivery:
    container_name: delivery
    build: ./delivery
    volumes: 
      - ./delivery:/app
#    ports:
#      - 8004:8000
    environment:
      GUNICORN_PORT: '${GUNICORN_PORT}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI_DELIVERY}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
    restart: on-failure
    depends_on:
      - rabbitmq
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15691:15691
      - 15672:15672
      - 5672:5672
