version: '3'
services:
  rabbitmq:
    build: . 
          #    environment:
    volumes:
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./certs/:/etc/rabbitmq/certs/
    ports:
      - 5671:5671
      - 61614:61614
      - 15671:15671
      - 5672:5672
